### ISSUE TITLE
PyInstaller doesn't seem to be installing

### ISSUE THREAD

**Issue by natemarks** [elgertam/cookiecutter-pipenv#11]
2/2/2019

cookcutter version 1.6.0

* Python version:  2.7.15, 3.6.8, 3.5.6, 3.4.9

CentOS 

Used the template with click and  pytest.  it added the Pipfile  line pyinstaller="*" and the PyInstaller failed to install in all  tox environments. everything worked when I removed PyInstaller from the Pipfile.  I'm not familiar with PyInstaller, but it may be causing problems for others

Here's the failure output:

[root@199f3c68c6f7 tinker_tox]# tox
GLOB sdist-make: /root/tinker_tox/setup.py
py27 recreate: /root/tinker_tox/.tox/py27
py27 installdeps: pipenv
py27 inst: /root/tinker_tox/.tox/.tmp/package/1/tinker_tox-0.1.0.zip
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,certifi==2018.11.29,Click==7.0,enum34==1.1.6,pipenv==2018.11.26,tinker-tox==0.1.0,typing==3.6.6,virtualenv==16.3.0,virtualenv-clone==0.5.1
py27 run-test-pre: PYTHONHASHSEED='1246730205'
py27 runtests: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3ae07)...
An error occurred while installing pyinstaller==3.4 --hash=sha256:a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 63/63 — 00:00:21
Installing initially failed dependencies...
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pyinstaller==3.4 (from -r /tmp/pipenv-CWZ_ma-requirements/pipenv-AJfZad-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'done'", '  Getting requirements to build wheel: started', "  Getting requirements to build wheel: finished with status 'error'", '  Complete output from command /root/tinker_tox/.tox/py27/bin/python /root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp19R9M:', '  Traceback (most recent call last):', '    File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>', '      main()', '    File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main', "      json_out['return_val'] = hook(**hook_input['kwargs'])", '    File "/root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel', '      return hook(config_settings)', '    File "/tmp/pip-build-env-RMSn7Q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel', "      return _get_build_requires(config_settings, requirements=['wheel'])", '    File "/tmp/pip-build-env-RMSn7Q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires', '      _run_setup()', '    File "/tmp/pip-build-env-RMSn7Q/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 85, in _run_setup', "      exec(compile(code, __file__, 'exec'), locals())", '    File "setup.py", line 20, in <module>', '      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM', '  ImportError: No module named PyInstaller', '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ["DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.", 'Command "/root/tinker_tox/.tox/py27/bin/python /root/tinker_tox/.tox/py27/lib/python2.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpp19R9M" failed with error code 1 in /tmp/pip-install-tFe0PY/pyinstaller']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:03
ERROR: InvocationError for command '/root/tinker_tox/.tox/py27/bin/pipenv install --dev' (exited with code 1)
py34 inst-nodeps: /root/tinker_tox/.tox/.tmp/package/1/tinker_tox-0.1.0.zip
py34 installed: DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).,alabaster==0.7.12,altgraph==0.16.1,argh==0.26.2,atomicwrites==1.3.0,attrs==18.2.0,Babel==2.6.0,bleach==3.1.0,bumpversion==0.5.3,certifi==2018.11.29,chardet==3.0.4,Click==7.0,coverage==4.5.2,dis3==0.1.3,docutils==0.14,entrypoints==0.3,filelock==3.0.10,flake8==3.7.4,future==0.17.1,idna==2.8,imagesize==1.1.0,Jinja2==2.10,macholib==1.11,MarkupSafe==1.1.0,mccabe==0.6.1,more-itertools==5.0.0,packaging==19.0,pathlib2==2.3.3,pathtools==0.1.2,pefile==2018.8.8,pipenv==2018.11.26,pkginfo==1.5.0.1,pluggy==0.8.1,py==1.7.0,pycodestyle==2.5.0,pyflakes==2.1.0,Pygments==2.3.1,pyparsing==2.3.1,pytest==4.2.0,pytest-runner==4.2,pytz==2018.9,PyYAML==3.13,readme-renderer==24.0,requests==2.21.0,requests-toolbelt==0.9.1,scandir==1.9.0,six==1.12.0,snowballstemmer==1.2.1,Sphinx==1.8.3,sphinxcontrib-websupport==1.1.0,tinker-tox==0.1.0,toml==0.10.0,tox==3.7.0,tqdm==4.30.0,twine==1.12.1,typing==3.6.6,urllib3==1.24.1,virtualenv==16.3.0,virtualenv-clone==0.5.1,watchdog==0.9.0,webencodings==0.5.1
py34 run-test-pre: PYTHONHASHSEED='1246730205'
py34 runtests: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3ae07)…
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Ignoring configparser: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
An error occurred while installing pyinstaller==3.4 --hash=sha256:a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 63/63 — 00:00:20
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Ignoring funcsigs: markers 'python_version < "3.0"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Ignoring functools32: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pyinstaller==3.4 (from -r /tmp/pipenv-x8f1dbrn-requirements/pipenv-tisns112-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'done'", '  Getting requirements to build wheel: started', "  Getting requirements to build wheel: finished with status 'error'", '  Complete output from command /root/tinker_tox/.tox/py34/bin/python3.4 /root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphh4nvwvs:', '  Traceback (most recent call last):', '    File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>', '      main()', '    File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main', "      json_out['return_val'] = hook(**hook_input['kwargs'])", '    File "/root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel', '      return hook(config_settings)', '    File "/tmp/pip-build-env-_znv4349/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel', "      return _get_build_requires(config_settings, requirements=['wheel'])", '    File "/tmp/pip-build-env-_znv4349/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires', '      _run_setup()', '    File "/tmp/pip-build-env-_znv4349/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 85, in _run_setup', "      exec(compile(code, __file__, 'exec'), locals())", '    File "setup.py", line 20, in <module>', '      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM', "  ImportError: No module named 'PyInstaller'", '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ["DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).", 'Command "/root/tinker_tox/.tox/py34/bin/python3.4 /root/tinker_tox/.tox/py34/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmphh4nvwvs" failed with error code 1 in /tmp/pip-install-fdqtosji/pyinstaller']
ERROR: ERROR: Package installation failed...
ERROR: InvocationError for command '/root/tinker_tox/.tox/py34/bin/pipenv install --dev' (exited with code 1)
py35 inst-nodeps: /root/tinker_tox/.tox/.tmp/package/1/tinker_tox-0.1.0.zip
py35 installed: alabaster==0.7.12,altgraph==0.16.1,argh==0.26.2,atomicwrites==1.3.0,attrs==18.2.0,Babel==2.6.0,bleach==3.1.0,bumpversion==0.5.3,certifi==2018.11.29,chardet==3.0.4,Click==7.0,coverage==4.5.2,dis3==0.1.3,docutils==0.14,entrypoints==0.3,filelock==3.0.10,flake8==3.7.4,future==0.17.1,idna==2.8,imagesize==1.1.0,Jinja2==2.10,macholib==1.11,MarkupSafe==1.1.0,mccabe==0.6.1,more-itertools==5.0.0,packaging==19.0,pathlib2==2.3.3,pathtools==0.1.2,pefile==2018.8.8,pipenv==2018.11.26,pkginfo==1.5.0.1,pluggy==0.8.1,py==1.7.0,pycodestyle==2.5.0,pyflakes==2.1.0,Pygments==2.3.1,pyparsing==2.3.1,pytest==4.2.0,pytest-runner==4.2,pytz==2018.9,PyYAML==3.13,readme-renderer==24.0,requests==2.21.0,requests-toolbelt==0.9.1,six==1.12.0,snowballstemmer==1.2.1,Sphinx==1.8.3,sphinxcontrib-websupport==1.1.0,tinker-tox==0.1.0,toml==0.10.0,tox==3.7.0,tqdm==4.30.0,twine==1.12.1,urllib3==1.24.1,virtualenv==16.3.0,virtualenv-clone==0.5.1,watchdog==0.9.0,webencodings==0.5.1
py35 run-test-pre: PYTHONHASHSEED='1246730205'
py35 runtests: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3ae07)…
Ignoring scandir: markers 'python_version < "3.5"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring configparser: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
An error occurred while installing pyinstaller==3.4 --hash=sha256:a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b! Will try again.
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 63/63 — 00:00:20
Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring funcsigs: markers 'python_version < "3.0"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring functools32: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pyinstaller==3.4 (from -r /tmp/pipenv-vgvimygh-requirements/pipenv-8zwb_zin-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'done'", '  Getting requirements to build wheel: started', "  Getting requirements to build wheel: finished with status 'error'", '  Complete output from command /root/tinker_tox/.tox/py35/bin/python3.5 /root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsvl9ppna:', '  Traceback (most recent call last):', '    File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>', '      main()', '    File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main', "      json_out['return_val'] = hook(**hook_input['kwargs'])", '    File "/root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel', '      return hook(config_settings)', '    File "/tmp/pip-build-env-o3jy7bkz/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel', "      return _get_build_requires(config_settings, requirements=['wheel'])", '    File "/tmp/pip-build-env-o3jy7bkz/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires', '      _run_setup()', '    File "/tmp/pip-build-env-o3jy7bkz/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 85, in _run_setup', "      exec(compile(code, __file__, 'exec'), locals())", '    File "setup.py", line 20, in <module>', '      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM', "  ImportError: No module named 'PyInstaller'", '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Command "/root/tinker_tox/.tox/py35/bin/python3.5 /root/tinker_tox/.tox/py35/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsvl9ppna" failed with error code 1 in /tmp/pip-install-wlsjndry/pyinstaller']
ERROR: ERROR: Package installation failed...
ERROR: InvocationError for command '/root/tinker_tox/.tox/py35/bin/pipenv install --dev' (exited with code 1)
py36 recreate: /root/tinker_tox/.tox/py36
py36 installdeps: pipenv
py36 inst: /root/tinker_tox/.tox/.tmp/package/1/tinker_tox-0.1.0.zip
py36 installed: certifi==2018.11.29,Click==7.0,pipenv==2018.11.26,tinker-tox==0.1.0,virtualenv==16.3.0,virtualenv-clone==0.5.1
py36 run-test-pre: PYTHONHASHSEED='1246730205'
py36 runtests: commands[0] | pipenv install --dev
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing dependencies from Pipfile.lock (f3ae07)…
Ignoring configparser: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring enum34: markers 'python_version < "3.4"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring funcsigs: markers 'python_version < "3.0"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring functools32: markers 'python_version < "3.2"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Ignoring pathlib2: markers 'python_version < "3.6"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
An error occurred while installing pyinstaller==3.4 --hash=sha256:a5a6e04a66abfcf8761e89a2ebad937919c6be33a7b8963e1a961b55cb35986b! Will try again.
Ignoring scandir: markers 'python_version < "3.5"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 63/63 — 00:00:24
Ignoring typing: markers 'python_version < "3.5"' don't match your environment
Looking in indexes: https://pypi.python.org/simple
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Looking in indexes: https://pypi.python.org/simple', 'Collecting pyinstaller==3.4 (from -r /tmp/pipenv-cbdk380p-requirements/pipenv-bu8eg3jk-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'done'", '  Getting requirements to build wheel: started', "  Getting requirements to build wheel: finished with status 'error'", '  Complete output from command /root/tinker_tox/.tox/py36/bin/python3.6 /root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpf938sy3_:', '  Traceback (most recent call last):', '    File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>', '      main()', '    File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main', "      json_out['return_val'] = hook(**hook_input['kwargs'])", '    File "/root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel', '      return hook(config_settings)', '    File "/tmp/pip-build-env-cm9mcg6d/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel', "      return _get_build_requires(config_settings, requirements=['wheel'])", '    File "/tmp/pip-build-env-cm9mcg6d/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires', '      _run_setup()', '    File "/tmp/pip-build-env-cm9mcg6d/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup', "      exec(compile(code, __file__, 'exec'), locals())", '    File "setup.py", line 20, in <module>', '      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM', "  ModuleNotFoundError: No module named 'PyInstaller'", '  ', '  ----------------------------------------']
[pipenv.exceptions.InstallError]: ['Command "/root/tinker_tox/.tox/py36/bin/python3.6 /root/tinker_tox/.tox/py36/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpf938sy3_" failed with error code 1 in /tmp/pip-install-bsbslhw2/pyinstaller']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:03
ERROR: InvocationError for command '/root/tinker_tox/.tox/py36/bin/pipenv install --dev' (exited with code 1)
flake8 recreate: /root/tinker_tox/.tox/flake8
flake8 installdeps: flake8
flake8 inst: /root/tinker_tox/.tox/.tmp/package/1/tinker_tox-0.1.0.zip
flake8 installed: Click==7.0,entrypoints==0.3,flake8==3.7.4,mccabe==0.6.1,pycodestyle==2.5.0,pyflakes==2.1.0,tinker-tox==0.1.0
flake8 run-test-pre: PYTHONHASHSEED='1246730205'
flake8 runtests: commands[0] | flake8 tinker_tox
_________________________________________________________________________________________________________________________________________ summary _________________________________________________________________________________________________________________________________________
ERROR:   py27: commands failed
ERROR:   py34: commands failed
ERROR:   py35: commands failed
ERROR:   py36: commands failed
  flake8: commands succeeded

**Comment by elgertam** [comment]
@natemarks I have attempted to replicate this using the `centos` Docker image (using Centos 7), and I did not have these issues installing `PyInstaller`. Can you give me any other details about your environment?
