### ISSUE TITLE
Question in gitignore 

### ISSUE THREAD

**Issue by Chris-May** [elgertam/cookiecutter-pipenv#2]
Hey Andrew!
I was curious about this line in the `.gitignore`. Should it be `*.cover`, or is there something I don't know about?

https://github.com/elgertam/cookiecutter-pipenv/blob/494e476bc764d1943c95b11806fe9a6821ac95d0/.gitignore#L72

**Comment by elgertam** [comment]
Yeah, that's a bug. I can fix or I can accept a PR if you'd like the credit.
